### PR TITLE
Remove unused python_path and related checks

### PR DESCRIPTION
**Pull request by uranusjr**
See https://github.com/pipxproject/pipx/pull/624#issuecomment-774955205

### CODE REVIEW

**Comment by itsayellow** [comment]
I think this code is actually doing something useful, and maybe it shouldn't be removed.  (I may have added it?)  It's not that we need the python path for the listing process, but it's one of the checks that `pipx list` does to make sure that each venv doesn't have any problems.

**Comment by uranusjr** [comment]
At least the check in `_get_list_output` can be removed though. It is unreachable because all invalid cases are caught in the other check.

**Comment by uranusjr** [comment]
I’ve restored the check in `get_package_summary`; only the check in `_get_list_output` is removed in this PR now.

**Review by itsayellow — APPROVED** [review]
Right, this looks good.

**Comment by itsayellow** [comment]
BTW, I'm letting you merge your own PRs once they've been approved.  That's the convention we've been using.

**Pull request merged**
