### PR TITLE
Fix Jacob Moss Twitter link

### PR DESCRIPTION
**Pull request by pscosta5**
Fix the incorrect link in Jacob Moss' quote.

### CODE REVIEW

**Comment by itsayellow** [comment]
Thanks for the fix!

Actually `README.md` is generated from `templates/index.md`.  Could you undo the change to `README.md`, and then make the same change in `templates/index.md`?

**Comment by uranusjr** [comment]
I just realised we are using a weird rendition of the name. Jacob’s last name is Kaplan-Moss. This would probably be as good a chance as any to fix it.

**Comment by pscosta5** [comment]
@itsayellow Whopps! I got it mixed up and thought it was the other way around. Will fix.

@uranusjr I'll correct his last name as well—good catch!

**Comment by pscosta5** [comment]
Is the CI failure related to #358?

**Comment by pscosta5** [comment]
Yeah seems so, I'll merge in those changes into my branch after #358 makes it into master.

**Comment by itsayellow** [comment]
OK #358 is merged, can you try to merge master into your branch and hopefully the docs test won't fail anymore.

**Comment by cs01** [comment]
> Fix the incorrect link in Jacob Moss' quote.

> I just realized we are using a weird rendition of the name. Jacob’s last name is Kaplan-Moss. This would probably be as good a chance as any to fix it.

I thoroughly screwed up adding that quote :sweat_smile:.

---

I just merged a change that lets you modify the README directly. It caused conflicts with this branch. If you want to fix, feel free, otherwise I don't mind. Sorry about the churn, I wanted to make this easier for future PRs.

**Comment by pscosta5** [comment]
@cs01 Not a problem! Switched the edit (back) to the README.

**Comment by cs01** [comment]
Cool, thank you

**Pull request merged**
