### PR TITLE
Add isort to lint nox session, fix import order inside pipx files

### LINKED ISSUE #257: add isort to lint tests
**How would this feature be useful?**

Ensure imports have been autosorted will make code consistent/readable and save time for developers.

**Describe the solution you'd like**

Use `isort` and https://github.com/asottile/seed-isort-config in the nox `lint` session. Also add a new nox session `format` to automatically run black, isort, and anything else we add.

Something like
```
    session.run("seed-isort-config", "--application-directories=pipx")
    session.run("isort", "--project=pipx", "--recursive", "--apply", *source_files)
```

**Describe alternatives you've considered**

Manually run isort, which is what I've been currently doing.

### PR DESCRIPTION
**Pull request by itsayellow**
* [ ] I have added an entry to `docs/changelog.md`

## Summary of changes
This adds isort checking to our lint nox session.  If imports are not sorted properly, the lint session will return a diff instructing the user how they need to rearrange their import statements.

I corrected the import order in all python files via isort .  I also changed the couple of files with relative imports to use absolute imports.

I added the `scripts/` subdirectory to lint checking.

Question for @cs01: I noticed that `setup.py` imports both `re` and `ast` and it seems like they are never used.  Am I missing something?  Are they actually used somehow?  If not I'll remove them.

Fixes #257 

## Test plan

Tested by running
```
# command(s) to exercise these changes
```

### CODE REVIEW

**Comment by cs01** [comment]
I tried to use isort before but I remember it was “unstable”. Each time I ran it, it sorted things differently so I gave up. Maybe it’s improved since then or you have a better configuration for it.

**Review by cs01 — APPROVED** [review]
Lgtm besides the unused imports in setup.py

**Comment by itsayellow** [comment]
> I tried to use isort before but I remember it was “unstable”. Each time I ran it, it sorted things differently so I gave up. Maybe it’s improved since then or you have a better configuration for it.

I've been using it for months now with pre-commit, and its been sorting all of my commits.  So far so good for me, it seems stable.  I haven't noticed any strange sorting behavior.

**Comment by itsayellow** [comment]
> If they aren’t directly used in the file then they aren’t used anymore. Must have been something in the past that got removed that used them.

I finally tracked them down.  They used to be used in `get_version()`

**Pull request merged**
