### PR TITLE
0.15.1.1

### PR DESCRIPTION
**Pull request by itsayellow**
Published to pypi.

### CODE REVIEW

**Comment by itsayellow** [comment]
Publishing to PyPI seemed to work fine.

I think `nox -s publish_docs` published to MY github account pages `https://itsayellow.github.io/pipx/`

```
carvel:pipx /Users/mclapp/Library/Python/3.7/bin/nox -s publish_docs
nox > Running session publish_docs
nox > Creating virtual environment (virtualenv) using python3.7 in .nox/publish_docs
nox > pip install . jinja2 mkdocs mkdocs-material
nox > python generate_docs.py
nox > mkdocs gh-deploy
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/mclapp/git/pipx/site 
WARNING -  Version check skipped: No version specificed in previous deployment. 
INFO    -  Copying '/Users/mclapp/git/pipx/site' to 'gh-pages' branch and pushing to GitHub. 
INFO    -  Your documentation should shortly be available at: https://itsayellow.github.io/pipx/ 
nox > Session publish_docs was successful.
```

**Comment by itsayellow** [comment]
Also it looks like previous edits to the Contributing page haven't showed up on https://pipxproject.github.io/pipx/contributing/

**Comment by itsayellow** [comment]
So to publish everything from pipxproject/pipx from master, I assume that requires special permissions that I don't have?  Or is there someway I have access to pipxproject/pipx ?

**Comment by cs01** [comment]
The docs are served from the gh-pages branch, which you may have access to commit to directly.

**Comment by itsayellow** [comment]
Can you add a release?  I don't think I'm able to do that.

**Comment by cs01** [comment]
Sure, what was the commit you uploaded to PyPI?

**Comment by itsayellow** [comment]
Basically the last commit of this PR was what I uploaded to PyPI.

**Comment by itsayellow** [comment]
I *think* I just fixed the docs on https://pipxproject.github.io/pipx/ .

What I did was make my `gh-pages` branch track `upstream/gh-pages` and then ran
```
nox -s docs
nox -s publish_docs
```

I think the docs are updated properly now on https://pipxproject.github.io/pipx/

Let me know if that is improper or wrong.

**Comment by itsayellow** [comment]
> I _think_ I just fixed the docs on https://pipxproject.github.io/pipx/ .

Actually it appears that I'm not allowed to push to pipxproject/pipx.git, so I did not update the docs.

**Pull request merged**
