### PR TITLE
moved 'upgrade' and 'upgrade_all' to commands/upgrade.py

### PR DESCRIPTION
**Pull request by ptisserand**
This pull request is the first one for issue #255 

Only upgrade and upgrade_all commands have been moved in a separate file.

### CODE REVIEW

**Comment by ptisserand** [comment]
Hi, any feedback about this pull request ?

**Comment by cs01** [comment]
This looks good besides the merge conflict.

**Comment by cs01** [comment]
A force push was recently done, so this PR will have to be rebased onto origin/master. Apologies for the inconvenience. See https://github.com/pipxproject/pipx/issues/270.

**Comment by ptisserand** [comment]
Hi, I have updated my branch but I don't get it why CI test is now failing.
I have tried master branch and failure is also present...

**Comment by cs01** [comment]
That is a known issue being dealt with across the python ecosystem. See https://github.com/pipxproject/pipx/issues/266 and the linked issue at the bottom. 

When https://github.com/pipxproject/pipx/pull/269 is merged the issue will be fixed. Your PR looks good though. I’ll merge it when the other fix lands. Thanks for your patience with all of this.

**Comment by ptisserand** [comment]
I have pushed a rebased version.

**Pull request merged**
