### PR TITLE
Remove dependency on packaging library

### PR DESCRIPTION
**Pull request by maxwell-k**
From these two comments I understand a PR removing the dependency on [packaging] would be welcome:

- <https://github.com/pipxproject/pipx/pull/361#issuecomment-583654680>
- <https://github.com/pipxproject/pipx/issues/339#issuecomment-583532860>

@clbarnes had already done a lot of work here, I only put together this short PR to make a small step forward.

I am enthusiastic `pipx` user and I maintain a [few packages] in the Alpine Linux distribution. I would like to see `pipx` packaged for Alpine Linux. As a first step I've been taking a look at the dependencies and a couple of PRs came to mind. This seemed to be a straightforward place to start.

[packaging]: https://pypi.org/project/packaging/
[few packages]: https://pkgs.alpinelinux.org/packages?name=&branch=edge&arch=x86_64&maintainer=Keith+Maxwell

<details>
<summary>Local testing</summary>

Clone the "pipx" source and start a container with access to that directory:

```sh
git clone git@github.com:pipxproject/pipx.git &&
cd pipx &&
podman run -ti -v .:/srv:z fedora:31
```

Inside the container run the tests:

```sh
cd /srv
dnf install --assumeyes python3-pip git
python3 -m pip install --upgrade pip
python3 -m pip install git+https://github.com/cs01/nox.git@5ea70723e9e6 nox
python3 -m pip install -e .
python3 src/pipx --version
pipx --version
rm -rf .nox  # to clear other runs (different Python versions or distributions)
nox -l
nox -s tests-3.7
```

To get output like:

```
✂
========================== 69 passed, 1 skipped in 225.59s (0:03:45) =====================================
nox > Session tests-3.7 was successful.
✂
nox > Session cover was successful.
nox > Ran multiple sessions:
nox > * tests-3.7: success
nox > * cover: success
```
Also run the linting:

```
$ nox --non-interactive --session "lint"
✂
Success: no issues found in 40 source files
✂
```

</details>

### CODE REVIEW

**Comment by maxwell-k** [comment]
CI is picking up on a formatting mistake I've made, I'll have that fixed ASAP.

**Comment by maxwell-k** [comment]
That's the CI passing; I didn't realise at first the project uses black. I am a fan too :-)

**Comment by cs01** [comment]
Thank you! Looks good to me. And thanks for helping get it packaged for Alpine Linux.

**Comment by joshuarli** [comment]
Nice cleanup!

**Pull request merged**
