### PR TITLE
update maintainer list

### PR DESCRIPTION
**Pull request by cs01**
Maintainer list was out of date

### CODE REVIEW

**Comment by itsayellow** [comment]
@cs01, I thought we were both lead maintainers?

**Review by gaborbernat — APPROVED** [review]

**Comment by cs01** [comment]
> @cs01, I thought we were both lead maintainers?

We are.

@gaborbernat thanks for the reviews. Could you please not merge them after approving?

**Comment by gaborbernat** [comment]
Ah, my bad. I'd expect in that case to be marked as draft PR.

**Comment by cs01** [comment]
> Ah, my bad. I'd expect in that case to be marked as draft PR.

That's a good call. I am trying to figure out the right expectations around when things should be merged or not. I personally like to merge my own PRs, but it probably varies from person to person.

**Comment by cs01** [comment]
We have a thing at my job where if you add the hashtag “#shipit” to the summary, and only then, does a reviewer have the ability to merge a PR. To me, marking as draft means “I want CI results, but don’t want anyone to review this”. I would like to adopt those conventions for pipx too. What do you think, does that work? Any thoughts or preferences @itsayellow?

**Comment by gaborbernat** [comment]
Sure. 👍

**Comment by itsayellow** [comment]
Yeah that sounds good to me too.

**Comment by itsayellow** [comment]
Yeah when I make something a Draft, in my mind it's so people can see what I'm doing and comment, but with the understanding that I'm not done yet.  But yes even if it's not a draft, I like the convention you're proposing.  Let's do that.

**Pull request merged**
