### PR TITLE
add env var USE_EMOJI

### LINKED ISSUE #376: Remove emojis by default
They don't really have any benefit, support is platform, specific, and they look unprofessional. Also half the time I get broken characters because I don't have the right emoji fonts installed. I don't really need any cutesy icons in my tooling.

I recognize that this is a very subjective thing, and having emojis doesn't really hurt anything, I just don't like them.

I'm not expecting any action to be taken here, just wanted to mention that I think they look bad. Maybe people can vote on this issue to give a better idea of how many people also think they look bad/good?

If you like the emoji please give this comment a thumbs down.

----

The environment variable `USE_EMOJI` will allow you to opt-out of emoji usage.

### PR DESCRIPTION
**Pull request by cs01**
fixes #376

cc @traverseda 

We had some trouble with https://github.com/pipxproject/pipx/pull/377 so I just made a new PR.

### CODE REVIEW

**Comment by itsayellow** [comment]
I'd still be happy with emoji-on by default, but I can live with it as an opt-in.  

My guess is that if emoji are opt-in, nobody will opt in and we almost may as well remove emoji support.

As a counterpoint to "emoji are a javascript thing" I'd like to point out that `black` uses emoji in its status messages.

**Comment by cs01** [comment]
This is emoji-on by default

**Comment by itsayellow** [comment]
> This is emoji-on by default

Ah ok!  Sorry I misunderstood.

**Comment by traverseda** [comment]
@itsayellow It would be nice if you could give a thumbs down on #376 since it would help maintainers get a better idea of what users/contributors actual preferences are? Not that I expect this project to be a straight democracy or be run by some kind of mob rule, just that it's good to gather data on it.

**Comment by itsayellow** [comment]
> @itsayellow It would be nice if you could give a thumbs down on #376 since it would help people get a better idea of what users/contributors actual preferences are? Not that I expect this project to be a straight democracy or be run by some kind of mob rule, just that it's good to gather data on it.

It's nice that you're soliciting broader response, thanks.  I put a thumbs down there, as requested, but in general my thumbs-down is mostly only for making emoji default off.  I don't have a problem with a mechanism that allows people to disable emoji.  Nor do I have a problem disabling it for platforms like Windows where the implementation can be problematic.

**Comment by traverseda** [comment]
> I put a thumbs down there, as requested, but in general my thumbs-down is mostly only for making emoji default off.

Of course, yeah. An option to disable emoji is completely non-controversial. Personally I'm happy with this solutions, and I'm not going to push very hard to default to disabling emoji. Originally that ticket was just "remove all emoji", I've edited it to instead be "default to no emoji".

Right now "remove all emoji" had overwhelming support, and I suspect that's not realistic. I'd like to get a better sample size so I can actually have relevant data on what people think of emoji. Of course selection bias would still be a major issue, because probably only people that have issues with emoji will seek out that ticket...

Still, worth noting down your feedback and I encourage anyone else who has an opinion do the same, so we can get slightly better data about it.

**Comment by cs01** [comment]
> Implementation looks fine to me. Could we have some tests?

Sure, I will add some

> Also I can use this to make the USE_EMOJI env variable the beginning of a standard, which is nice.

Sounds like you are on a quest to eradicate emojies! Haha. Glad to play a part in it.

**Pull request merged**
