### PR TITLE
Windows: uninstall: check if app file exists before unlinking

### PR DESCRIPTION
**Pull request by itsayellow**
* [x] I have added an entry to `docs/changelog.md`

## Summary of changes
Add a check on Windows if a file still exists before trying to unlink it during install.  This is important if the same app name shows up twice in the list of apps, and the app is deleted first before trying to delete it again.  Previously, this would result in a crash on Windows.

Possibly fixes and definitely pertains to #540 .

## Test plan

Tested by running on Windows:
```
> pipx install kaggle==1.5.9 --include-deps
  Overwriting file C:\Users\mclapp\.local\bin\slugify with C:\Users\mclapp\.local\pipx\venvs\kaggle\Scripts\slugify
done!
creating virtual environment...
installing kaggle from spec 'kaggle==1.5.9'...
  installed package kaggle 1.5.9, Python 3.9.0
  These apps are now globally available
    - chardetect.exe
    - kaggle.exe
    - slugify
    - slugify.exe
    - tqdm.exe
> pipx uninstall kaggle
uninstalled kaggle!
```

Previously, this would crash like so:
```
> pipx install kaggle==1.5.9 --include-deps
  Overwriting file C:\Users\mclapp\.local\bin\slugify with C:\Users\mclapp\.local\pipx\venvs\kaggle\Scripts\slugify
done!
creating virtual environment...
installing kaggle from spec 'kaggle==1.5.9'...
  installed package kaggle 1.5.9, Python 3.9.0
  These apps are now globally available
    - chardetect.exe
    - kaggle.exe
    - slugify
    - slugify.exe
    - tqdm.exe
> pipx uninstall kaggle
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mclapp\AppData\Roaming\Python\Python39\Scripts\pipx.exe\__main__.py", line 7, in <module>
  File "C:\Users\mclapp\AppData\Roaming\Python\Python39\site-packages\pipx\main.py", line 609, in cli
    return run_pipx_command(parsed_pipx_args)
  File "C:\Users\mclapp\AppData\Roaming\Python\Python39\site-packages\pipx\main.py", line 192, in run_pipx_command
    return commands.uninstall(venv_dir, constants.LOCAL_BIN_DIR, verbose)
  File "C:\Users\mclapp\AppData\Roaming\Python\Python39\site-packages\pipx\commands\uninstall.py", line 62, in uninstall
    file.unlink()
  File "c:\program files\python39\lib\pathlib.py", line 1343, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\mclapp\\.local\\bin\\slugify'
```

### CODE REVIEW

**Comment by uranusjr** [comment]
Is think specific to Windows? I imagine the same would apply on other platforms.

**Comment by itsayellow** [comment]
> Is this specific to Windows? I imagine the same would apply on other platforms.

Yes it's just windows, because there is a separate branch of code for symlinks (non-Windows) and copies (Windows).  On the symlink-branch, we actually check if the file exists before unlinking it.

Also, I did test it on macos and uninstall worked fine.

**Comment by itsayellow** [comment]
I also added a test that tests for this problem in `test_uninstall.py` with this PR.

**Comment by uranusjr** [comment]
Thanks for the clarification.

**Review by uranusjr — APPROVED** [review]

**Pull request merged**
