### PR TITLE
Upgrade: add option to upgrade injected packages

### LINKED ISSUE #79: Update injected packages.
As mentioned in #72, it's currently not possible to update dependencies/injected packages in pipx.

Should this be supported in some form? What form should this take?

`pipx update <foo>`

Should this update all injected packages and dependencies, or not?

### PR DESCRIPTION
**Pull request by itsayellow**
* [x] I have added an entry to `docs/changelog.md`

## Summary of changes

Adds `--include-injected` option to `upgrade` and `upgrade-all`, and if used upgrades all injected packages in the venv(s).  Without the `--include-injected` option `upgrade` and `upgrade-all` work as in the past.

Closes #79 

## Test plan

Tested by running
```shell
> pipx install pylint==2.5.3                           
  installed package pylint 2.5.3, Python 3.9.0
  These apps are now globally available
    - epylint
    - pylint
    - pyreverse
    - symilar
done! ✨ 🌟 ✨
> pipx inject pylint black==18.9.b0
  injected package black into venv pylint
done! ✨ 🌟 ✨
> pipx upgrade --include-injected pylint
upgraded package pylint from 2.5.3 to 2.6.0 (location: /Users/mclapp/.local/pipx/venvs/pylint)
upgraded package black from 18.9b0 to 20.8b1 (location: /Users/mclapp/.local/pipx/venvs/pylint)
> pipx uninstall pylint
uninstalled pylint! ✨ 🌟 ✨
> pipx install pylint==2.5.3            
  installed package pylint 2.5.3, Python 3.9.0
  These apps are now globally available
    - epylint
    - pylint
    - pyreverse
    - symilar
done! ✨ 🌟 ✨
> pipx inject pylint black==18.9.b0     
  injected package black into venv pylint
done! ✨ 🌟 ✨
> pipx upgrade pylint    
upgraded package pylint from 2.5.3 to 2.6.0 (location: /Users/mclapp/.local/pipx/venvs/pylint)
>
```

### CODE REVIEW

**Comment by itsayellow** [comment]
I used `--include-injected` because it exists for other pipx commands, but in general I like shorter options.  If people want I can use a different option switch.

**Comment by tobwen** [comment]
Sorry to file this bug here, but @itsayellow doesn't have activated _issues_.

The package _MapProxy_ gets installed into `/home/tobwen/.local/pipx/venvs/MapProxy`.

When trying to run `pipx upgrade --include-injected MapProxy`, I'm getting this error:
```
Removed file /home/tobwen/.local/pipx/logs/cmd_2020-11-27_18.19.11.log
Package is not installed. Expected to find //home/tobwen/.local/pipx/venvs/mapproxy, but it does not exist.
```

Seems like there's an issue with upper- and lower-case?

**Comment by itsayellow** [comment]
> Sorry to file this bug here, but @itsayellow doesn't have activated the _issues_ section.
> 
> The package _MapProxy_ gets installed into `/home/tobwen/.local/pipx/venvs/MapProxy`.
> 
> When trying to run `pipx upgrade --include-injected MapProxy`, I'm getting this error:
> 
> ```
> Removed file /home/tobwen/.local/pipx/logs/cmd_2020-11-27_18.19.11.log
> Package is not installed. Expected to find /home/tobwen/.local/pipx/venvs/mapproxy, but it does not exist.
> ```
> 
> Seems like there's an issue with upper- and lower-case?

This is a fine place to comment on a bug with this PR.  😃 

You're coming into contact with a change to pipx's behavior.  In a previous release pipx changed from internally using venv names that are exactly what the user typed, to using "normalized" names.

You should be able to fix your pipx internal data by using the development (unreleased as of yet) pipx and either executing `pipx reinstall MapProxy` or `pipx reinstall-all`.

The development version also will be ok if you still want to specify your venv as capitalized, e.g. `MapProxy`.

**Comment by tobwen** [comment]
Thank you for your reply and apologies for accusing you of creating a possible bug. As always, it has been a feature (of _pipx_) and not a bug :) Good hint, all packages were reinstalled and everything works now.

Thanks for this great PR, it'll make daily work a bit easier.

**Comment by itsayellow** [comment]
> Thank you for your reply and apologies for accusing you of creating a possible bug. As always, it has been a feature (of _pipx_) and not a bug :) Good hint, all packages were reinstalled and everything works now.
> 
> Thanks for this great PR, it'll make daily work a bit easier.

I won't derail the discussion here *too* much, but I will point out that thanks to your feedback I just added PR #570 which should help avoid issues like this in the future.  Thanks!

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
