### PR TITLE
Reinstall command

### LINKED ISSUE #256: Add `reinstall` command
**How would this feature be useful?**

per @sahensley 's comment in https://github.com/pipxproject/pipx/pull/246

> Also, a bit of a side trek but would it be worth introducing reinstall for an individual package? I could possible see a need if only certain venvs were made with a Python interpreter that is no longer present but it may be a bit of a niche case. The instance I've run into this when I've had multiple Python versions compiled via Pyenv.

**Describe the solution you'd like**

Add top-level `reinstall` command, as an alternative to the `reinstall-all` command.

**Describe alternatives you've considered**

Uninstall then reinstall the package, but that is not super very friendly.

### PR DESCRIPTION
**Pull request by itsayellow**
* [x] I have added an entry to `docs/changelog.md`

## Summary of changes
Adds a `reinstall` command to only reinstall one venv.

Closes #256 

## Test plan

Tested by running
```
pipx install pycowsay
pipx reinstall pycowsay
```

### CODE REVIEW

**Comment by itsayellow** [comment]
It would be simple to make this take multiple argument for multiple venvs.  I kept it at one venv because that matched the other pipx sub-commands.

**Comment by gaborbernat** [comment]
> Adds a `reinstall` command to only reinstall one venv.

Any reason why just not make this the behaviour of ``pipx install -f`` or ``pipx install --overwrite``?

**Comment by itsayellow** [comment]
> Any reason why just not make this the behaviour of `pipx install -f` or `pipx install --overwrite`?

One difference would be that this completely reinstalls the venv, including re-injecting all of the injected packages, while `install` is currently only charged with affecting the main package of a venv.  

This command also reuses all of the original options for the venv and installed packages like `pip_args`, `venv_args`, `install_dependencies` without forcing you to re-supply them on the command line, like `install` might imply you need to do.

**Comment by itsayellow** [comment]
I also just thought it would make sense to the user as an analog to `upgrade` / `upgrade-all`.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
