### PR TITLE
solve issues #96 and #98

### PR DESCRIPTION
**Pull request by Laurentiu-Andronache**

### CODE REVIEW

**Comment by Laurentiu-Andronache** [comment]
omfg it took me 30 minutes to understand how to do the damn pull request

it seems that a repository has to be forked first (that's how I was doing it before, but I didn't realize it's mandatory) 

I'll go ahead and start reading a pull request tutorial now: https://yangsu.github.io/pull-request-tutorial/

**Comment by cs01** [comment]
Thanks! Will take a look later tonight.

**Comment by Laurentiu-Andronache** [comment]
sry, it might be a stupid question: I'm struggling to submit a second pull request (I think I understand how now: I need to create a new branch first)

but are we supposed to submit pull requests to the master branch or to the dev branch?

**Comment by cs01** [comment]
Not a dumb question. Master branch.

**Comment by Laurentiu-Andronache** [comment]
I'll do the pull request again, I fucked up. I don't understand git.

**Pull request closed without merging**
