### PR TITLE
update docs and increment version

### PR DESCRIPTION
**Pull request by cs01**

### CODE REVIEW

**Comment by itsayellow** [comment]
Sorry coming late...
Should this have a github release as well?

**Comment by cs01** [comment]
No problem. Yes there should already be one. Is there not?

**Comment by itsayellow** [comment]
I see 15.3.1 but no 15.2.0 (which I assume is this version?)

**Comment by itsayellow** [comment]
Oh there are mini references to 15.2.0 and 15.3.0 in the Releases tab.  Not sure why they're different than other releases.  Does that mean they have a tag, but were not specifically added as a "Release"?

**Comment by cs01** [comment]
I pushed a tag directly but didn't make the release through github.

> Does that mean they have a tag, but were not specifically added as a "Release"?

Looks like that is the case.

**Pull request merged**
