### PR TITLE
0.15.1.2

### PR DESCRIPTION
**Pull request by itsayellow**
fixes app search in dependencies, fixes minor bug in upgrade-all

### CODE REVIEW

**Comment by itsayellow** [comment]
I could successfully `publish_docs` after:
* change url for remote `upstream` from `https://github.com/pipxproject/pipx.git` to `git@github.com:pipxproject/pipx.git`
* `git checkout --track upstream/gh-pages`
* checkout `master`, run `nox -s publish_docs`
* checkout `gh-pages`, manually push

`nox -s publish_docs` says it is pushing, but somehow nothing showed up on the pipxproject/pipx gh-pages branch until I manually pushed.  Not sure why.

**Comment by cs01** [comment]
Is it using the mkdocs.yml configuration? If not, maybe that will fix it. If so, maybe it can be tweaked?

**Comment by cs01** [comment]
Congrats on doing a pipx release on your own 🎉

**Comment by itsayellow** [comment]
> Is it using the mkdocs.yml configuration? If not, maybe that will fix it. If so, maybe it can be tweaked?

From my reading of the mkdocs documentation, it should use it if it's in the project dir.  But I don't see anything in pipx's `mkdocs.yml` that pertains to gh-deploy, so maybe we need to configure more?

**Comment by itsayellow** [comment]
Ah I see what happened.  Even though I specifically made my gh-pages branch track upstream/gh-pages, `mkdocs gh-deploy` still seems to have specifically pushed to origin/gh-pages.

Ah and I see why.  https://www.mkdocs.org/user-guide/configuration/#remote_name  `remote_name` defaults to origin for gh-deploy.  Let me make a pull request to fix mkdocs.yml.

**Pull request merged**
