### PR TITLE
Disable emoji unless explicitly enabled by the user

### PR DESCRIPTION
**Pull request by traverseda**

### CODE REVIEW

**Comment by traverseda** [comment]
As per #376

**Comment by cs01** [comment]
Is `USE_EMOJI` a common environment variable used more broadly?

**Comment by traverseda** [comment]
Nope, I just tried to pick a name that expressed the sentiment well, and then realized that other projects might arrive at a similar name, and that we'd want a way to deal with it on a per-project basis.

**Comment by traverseda** [comment]
Like I say, this is a personal preference thing. It might be more in-line with the projects goals if it defaulted there being emoji, a `NO_EMOJI` flag instead...

That also isn't a flag that's in use anywhere, and I worry that it's a bit of a stronger case. To me `NO_EMOJI` says "absolutely no emoji under any circumstances", where as `USE_EMOJI` doesn't have that same connotation. Maybe a `NO_EXTRA_EMOJI` flag if you want to default to there being emoji?

**Comment by itsayellow** [comment]
Personally I like the emojis we use, so my vote would be for default-on emojis.

That being said, I have seen cases (like using a less-capable shell on Windows) where they are broken, and it would be nice if we disabled emojis automatically in more situations and/or had a user way of opting out.

**Comment by itsayellow** [comment]
A conservative approach might be `PIPX_NO_EMOJI` since there is no overall standard and no indication that other apps would find such an env variable useful.

**Comment by traverseda** [comment]
There's never going to be a formal standard for this, the best we're going to get is if tools start settling on something. It might as well start with this tool, so I'd *strongly* prefer a generic env var so if I bug other projects about removing emoji from their cli tool I can point at this and say "look, here's an informal standard". 

Well let's look at some other projects that use emoji, to get an idea of the kind of tone that using emoji in your project sets?

https://www.google.com/search?q="🔥"%20site:github.com

https://www.google.com/search?q="🚀"%20site:github.com

**Comment by traverseda** [comment]
Use of emoji is very much a part of the javascript culture, and I have a *strong* dislike of javascript tooling, so 90% of the reason I don't like emoji in my python tooling is because it's subconsciously making me think this tool is doing things the "javascript way".

If I had to give an actual defense, beyond just "I don't like it", I'd say that using emoji in cli output is not idiomatic python. It's writing python tools like they're javascript tools.

But ultimately it's an aesthetic thing that doesn't matter too much.

**Comment by traverseda** [comment]
How about defaulting to true?

`emoji_support = os.environ.get('PIPX_USE_EMOJI',os.environ.get('USE_EMOJI', True))`

So that `USE_EMOJI=""` will be our false value, but an unset `USE_EMOJI` variable is still defaults to the current behavior.

I'd have to add back in support for the default being whatever the platform default is, so in reality it would be 

```python
platform_emoji_support = not WINDOWS and sys.getdefaultencoding() == "utf-8"
# The "USE_EMOJI" environment variable allows you to override default emoji behavior.
# Optionally over-ride `USE_EMOJI` with the more specific `PIPX_USE_EMOJI` value.
emoji_support = os.environ.get('PIPX_USE_EMOJI',os.environ.get('USE_EMOJI', platform_emoji_support))
```

**Comment by cs01** [comment]
I like the idea of emoji by default (`USE_EMJOI` is true), but can be turned off with the env var. I don't see a need to add in any other env vars. If you update the PR with that behavior I will merge it.

**Comment by traverseda** [comment]
Done, `USE_EMOJI` defaults to platform default. Setting the env variable to an empty string disabled emoji regardless of platform default, and setting it to anything else force enabled emoji.

**Comment by clbarnes** [comment]
As we're defaulting to using emoji where possible, would it make more sense for the environment variable, which will only ever be defined to prevent theuse of emoji, to be `DISABLE_EMOJI`?

**Comment by traverseda** [comment]
I do like `DISABLE_EMOJI` more than `NO_EMOJI`, I'd also consider `LESS_EMOJI`. Obviously I have the bias that I'd like to eventually move projects towards an opt-in standard.

**Comment by cs01** [comment]
`DISABLE_EMOJI` is fine with me too. Maybe make it plural, `DISABLE_EMOJIS`.

**Comment by clbarnes** [comment]
Consensus on the internet seems to be that either is an acceptable plural, leaning slightly in favour of "emoji" in written contexts. I say go for fewer characters if it's equally valid.

**Comment by clbarnes** [comment]
Consensus on the internet seems to be that either is an acceptable plural, leaning slightly in favour of "emoji" in written contexts. I say go for fewer characters if it's equally valid.

**Comment by cs01** [comment]
> Personally I like the emojis we use, so my vote would be for default-on emojis.
> 
> That being said, I have seen cases (like using a less-capable shell on Windows) where they are broken, and it would be nice if we disabled emojis automatically in more situations and/or had a user way of opting out.

Let's choose a set of rules to turn on emoji's in only the most conservative of use cases. Something like: os is not windows, and `$LANG` ends with `.UTF-8`.

**Comment by cs01** [comment]
This is basically ready to merge. Just need to run `black` on pipx/src/pipx/constants.py.

**Comment by traverseda** [comment]
>This is basically ready to merge. Just need to run black on pipx/src/pipx/constants.py.

Sorry, I somehow missed this message or I would have done the formatting myself.

**Comment by cs01** [comment]
I have a branch I'm trying to update this PR with but I am getting some permission errors. Want to try to re-push to this PR with the contents of the branch cs01/disable-emoji?

**Comment by traverseda** [comment]
Yep

**Comment by traverseda** [comment]
Well it is done for what that's worth, doesn't seem to be updating. Maybe open the PR back up and try again?

**Comment by cs01** [comment]
Now travis isn't building. New PR here https://github.com/pipxproject/pipx/pull/398.

**Pull request closed without merging**
